<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\starshine-abp\modules\identity\src\Starshine.Abp.Identity.Application\Starshine.Abp.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\starshine-abp\modules\tenant-management\src\Starshine.Abp.TenantManagement.Application\Starshine.Abp.TenantManagement.Application.csproj" />
    <ProjectReference Include="..\Starshine.Authservice.Application.Contracts\Starshine.Authservice.Application.Contracts.csproj" />
    <ProjectReference Include="..\Starshine.Authservice.Domain\Starshine.Authservice.Domain.csproj" />
  </ItemGroup>

</Project>
