<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.Ddd.Domain.Shared" Version="8.3.4" />
		<PackageReference Include="Volo.Abp.BackgroundJobs.Domain.Shared" Version="8.3.4" />
		<PackageReference Include="Volo.Abp.AuditLogging.Domain.Shared" Version="8.3.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\starshine-abp\framework\src\Starshine.Abp.Core\Starshine.Abp.Core.csproj" />
	  <ProjectReference Include="..\..\..\starshine-abp\modules\identityserver\src\Starshine.Abp.IdentityServer.Domain.Shared\Starshine.Abp.IdentityServer.Domain.Shared.csproj" />
	  <ProjectReference Include="..\..\..\starshine-abp\modules\identity\src\Starshine.Abp.Identity.Domain.Shared\Starshine.Abp.Identity.Domain.Shared.csproj" />
	  <ProjectReference Include="..\..\..\starshine-abp\modules\permission-management\src\Starshine.Abp.PermissionManagement.Domain.Shared\Starshine.Abp.PermissionManagement.Domain.Shared.csproj" />
	  <ProjectReference Include="..\..\..\starshine-abp\modules\tenant-management\src\Starshine.Abp.TenantManagement.Domain.Shared\Starshine.Abp.TenantManagement.Domain.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Options\" />
	</ItemGroup>

</Project>
